//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace D3BuildMarkSite {
    
    
    public partial class BuildCompareView {
        
        /// <summary>
        /// uxBuildSnapshotView1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::D3BuildMarkSite.Controls.uxBuildSnapshotView uxBuildSnapshotView1;
        
        /// <summary>
        /// ViewBuildSnapshotAlt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::D3BuildMarkSite.Controls.ViewBuildSnapshotAlt ViewBuildSnapshotAlt;
    }
}
